### ISSUE TITLE
License

### ISSUE THREAD

**Issue by eligiblekeng** [hubotio/hubot-diagnostics#3]
Hi, in your `npm` and `package.json` it's mentioned that this is under the MIT license, however there is none attached. Would you guys mind putting a `LICENSE` up?

**Comment by technicalpickles** [comment]
This package was generated with https://github.com/github/generator-hubot so that probably needs to be updated. Also, nearly all the packges on this org will need it too.

**Comment by technicalpickles** [comment]
This should still be fixed.
